spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saloumservicedb
    username: root
    password: saloum123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # options: validate, update, create, create-drop
    show-sql: true # Affiche les requêtes SQL générées dans la console
    properties:
      hibernate:
        format_sql: true # Formate les requêtes SQL générées pour plus de lisibilité
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always # Exécute les scripts de démarrage (schema.sql, data.sql) au démarrage

server:
  port: 8080 # Port sur lequel l'application tourne

logging:
  level:
    org:
      springframework:
        orm: DEBUG # Niveau de log pour les transactions ORM
